### ISSUE TITLE
[Product Feedback] 申請加入功能沒有確認使用者登入狀況

### ISSUE THREAD

**Issue by dlackty** [pine0113/hikingwish#2]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/14349/46573930-88c72a80-c9ce-11e8-92b9-df8b6e6bae02.png">

如上圖，會出現 500 error。

**Comment by clonn** [comment]
未登入下，按到『申請加入』會跳到 error page

**Comment by pine0113** [comment]
已新增申請登入驗證
